// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counter.sql

package queries

import (
	"context"
)

const GetCounter = `-- name: GetCounter :one
SELECT value
FROM counter
WHERE id = 1
`

func (q *Queries) GetCounter(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetCounter)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const IncrementAndGetCounter = `-- name: IncrementAndGetCounter :one
UPDATE counter
SET value = value + 1
WHERE id = 1
RETURNING value
`

func (q *Queries) IncrementAndGetCounter(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, IncrementAndGetCounter)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const IncrementCounter = `-- name: IncrementCounter :exec
UPDATE counter
SET value = value + 1
WHERE id = 1
`

func (q *Queries) IncrementCounter(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, IncrementCounter)
	return err
}
